
app:
  current-api-version: "/api/v1"
server:
  shutdown: graceful
springdoc:
  swagger-ui:
    path: /api-docs/swagger-ui.html
  api-docs:
    path: /api-docs
logging:
  level:
    ROOT: INFO
    http.wire-log: INFO
    org.zalando.logbook: INFO
