---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
  labels:
    app: ${APPLICATION_NAME}
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}
  ports:
    - protocol: TCP
      port: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: "50%"
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: naokiii/${APPLICATION_NAME}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-port
          resources:
            requests:
              cpu: 0.05
              memory: "512Mi"
            limits:
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 50
            periodSeconds: 10
            successThreshold: 1
      securityContext:
        runAsUser: 1001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    ingress.kubernetes.io/rewrite-target: /api/v1
spec:
  rules:
    - http:
        paths:
          - path: /api/v1
            backend:
              serviceName: $APPLICATION_NAME
              servicePort: 8080