---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
  labels:
    app: ${APPLICATION_NAME}
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}
  ports:
    - protocol: TCP
      port: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: "50%"
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: naokiii/${APPLICATION_NAME}:latest
          args: ["--spring.profiles.active=json-logging"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-port
          resources:
            requests:
              cpu: 0.05
              memory: "512Mi"
            limits:
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 50
            periodSeconds: 10
            successThreshold: 1
      securityContext:
        runAsUser: 1001
