name: CICD

on:
  push:
    branches:
      - main
      - feature/ci-cd-pipeline
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    name: java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f pom.xml clean compile
  build:
    runs-on: ubuntu-latest
    needs: compile
    name: build Maven project
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build and test project
        run: mvn -f pom.xml clean verify
      - name: upload Maven build artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            target/gross-pension-calculator-service-0.0.1-SNAPSHOT.jar
            Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    name: build & push docker image
#    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
    steps:
      - name: download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: naokiii/gross-pension-service:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  kubernetes:
    runs-on: ubuntu-latest
    needs: [ deploy ]
    name: rollout on kubernetes
    steps:
      - uses: actions/checkout@v1
      - name: insert variables to k8s files
        uses: danielr1996/envsubst-action@1.1.0
        env:
          APPLICATION_NAME: gross-pension-calculator-service
        with:
          input: src/main/k8s/deployment.yaml
          output: src/main/k8s/deployment-envsubst.yaml
      - name: rollout to kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -n gross-pension-calculator-service -f src/main/k8s/deployment-envsubst.yaml
      - name: verify rollout
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status -n gross-pension-calculator-service --timeout 5m --watch deployment/gross-pension-calculator-service

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    name: Build Docker container and deploy to Kubernetes
#    steps:
#      - uses: actions/checkout@v1
#      - name: Download Maven build artifact
#        uses: actions/download-artifact@v1
#        with:
#          name: artifact
#      - name: Build Docker container
#        run: |
#          mkdir -p github-actions-java-maven/target
#          mv artifact/github-actions-java-maven.jar github-actions-java-maven/target
#          docker build -t de.rieckpil.blog/github-actions-sample github-actions-java-maven
#      - name: Access secrets
#        env:
#          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
#        run: echo "Content of secret - $SUPER_SECRET"
#      - name: Push Docker images
#        run: echo "Pushing Docker image to Container Registry (e.g. ECR)"
#      - name: Deploy application
#        run: echo "Deploying application (e.g. Kubernetes)"